apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8443  
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:10.0.0
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_pass
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: keycloak-db-service
            - name: DB_DATABASE
              value: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_db_pass
            - name: KEYCLOAK_HTTP_PORT
              value: "80"
            - name: KEYCLOAK_HTTPS_PORT
              value: "443"
            - name: KEYCLOAK_HOSTNAME
              value: keycloak-pharme.dhc-lab.hpi.de
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto $scheme;

spec:
  rules:
    - host: keycloak-pharme.dhc-lab.hpi.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-svc
                port:
                  number: 8443
