---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:19.0.1
          args: ["start"]
          env:
            # Set admin credentials
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_pass
            # Proxy / hostname settings
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: keycloak-pharme.dhc-lab.hpi.de
            - name: KC_FRONTEND_URL
              value: https://keycloak-pharme.dhc-lab.hpi.de/auth
            - name: KC_HOSTNAME_STRICT
              value: "false"
            # Database credentials
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: keycloak-db-service
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: db
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_db_user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_db_pass
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: keycloak
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "KC_SC"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "false"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
spec:
  rules:
    - host: keycloak-pharme.dhc-lab.hpi.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
