coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 10%

flag_management:
  individual_flags:
    - name: annotation-server
      paths:
        - annotation-server/src
      carryforward: true
    - name: app
      paths:
        - app/lib
      carryforward: true
    - name: lab-server
      paths:
        - lab-server/src
      carryforward: true
