services:
    api:
        build:
            dockerfile: ./lab-server/Dockerfile
            context: ../
        ports:
            - 8081:3001
        depends_on:
            - lab-server-db
        profiles:
            - production
        restart: unless-stopped

    lab-server-db:
        image: postgres:13
        volumes:
            - lab_server_db:/var/lib/postgresql/data
        ports:
            - 6543:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=lab_server_db
        restart: unless-stopped

    keycloak:
        image: jboss/keycloak:16.1.0
        environment:
            DB_VENDOR: postgres
            DB_ADDR: keycloak-db
            DB_DATABASE: keycloak_db
            DB_USER: admin
            DB_PASSWORD: admin
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - 28080:8080
        depends_on:
            - keycloak-db
        restart: unless-stopped

    keycloak-db:
        image: postgres:13
        volumes:
            - keycloak_db:/var/lib/postgresql/data
        ports:
            - 25433:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=keycloak_db
        restart: unless-stopped

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: minio_admin
            MINIO_ROOT_PASSWORD: minio_admin
        volumes:
            - minio_db:/data
        ports:
            - 9000:9000
            - 9001:9001
        command: server /data --console-address ":9001"
        restart: unless-stopped

volumes:
    lab_server_db:
    minio_db:
    keycloak_db:
