services:
    api:
        build:
            dockerfile: ./lab-server/Dockerfile
            context: ../
        ports:
            - 8081:3001
        depends_on:
            - lab-server-db
        profiles:
            - production
        restart: unless-stopped

    lab-server-db:
        image: postgres:13
        volumes:
            - lab_server_db:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        restart: unless-stopped

    keycloak:
        image: jboss/keycloak:16.1.0
        environment:
            DB_VENDOR: postgres
            DB_ADDR: keycloak-db
            DB_DATABASE: ${KEYCLOAK_DB_NAME}
            DB_USER: ${KEYCLOAK_DB_USER}
            DB_PASSWORD: ${KEYCLOAK_DB_PASS}
            KEYCLOAK_USER: ${KEYCLOAK_USER}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
        ports:
            - 28080:8080
        depends_on:
            - keycloak-db
        restart: unless-stopped

    keycloak-db:
        image: postgres:13
        volumes:
            - keycloak_db:/var/lib/postgresql/data
        ports:
            - 25433:5432
        environment:
            - POSTGRES_USER=${KEYCLOAK_DB_USER}
            - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASS}
            - POSTGRES_DB=${KEYCLOAK_DB_NAME}
        restart: unless-stopped

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            - minio_db:/data
        ports:
            - ${MINIO_PORT}:9000
            - 9001:9001
        command: server /data --console-address ":9001"
        restart: unless-stopped

volumes:
    lab_server_db:
    minio_db:
    keycloak_db:
