services:
    api:
        build:
            dockerfile: ./lab-server/Dockerfile
            context: ../
        network_mode: host
        environment:
            - PORT=${PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
            - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
            - KEYCLOAK_REALM=${KEYCLOAK_REALM}
            - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
            - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
            - MINIO_PORT=${MINIO_PORT}
            - MINIO_ENDPOINT=${MINIO_ENDPOINT}
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        depends_on:
            - lab-server-db
        profiles:
            - production
        restart: unless-stopped

    lab-server-db:
        image: postgres:13
        volumes:
            - lab_server_db:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        restart: unless-stopped

    keycloak:
        image: quay.io/keycloak/keycloak:25.0.1
        environment:
            KC_DB: postgres
            KC_DB_URL_HOST: keycloak-db
            KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
            KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
            KC_DB_PASSWORD: ${KEYCLOAK_DB_PASS}
            KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASS}
            KC_HTTP_MANAGEMENT_PORT: 9000
            KC_HEALTH_ENABLED: true
        command: start-dev
        ports:
            - ${KEYCLOAK_PORT}:8080
            - ${KEYCLOAK_MANAGEMENT_PORT}:9000
        depends_on:
            - keycloak-db
        restart: unless-stopped

    keycloak-db:
        image: postgres:13
        volumes:
            - keycloak_db:/var/lib/postgresql/data
        ports:
            - 25433:5432
        environment:
            - POSTGRES_USER=${KEYCLOAK_DB_USER}
            - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASS}
            - POSTGRES_DB=${KEYCLOAK_DB_NAME}
        restart: unless-stopped

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            - minio_db:/data
        ports:
            - ${MINIO_PORT}:9000
            - ${MINIO_CONSOLE_PORT}:9001
        command: server /data --console-address ":9001"
        restart: unless-stopped

volumes:
    lab_server_db:
    minio_db:
    keycloak_db:
