name: app
description: A new Flutter project.
publish_to: "none"
version: 1.1.0+19

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.3.0"

dependencies:
  #json_annotation: ^4.8.1
  #collection: ^1.18.0
  path: ^1.9.0
  file_selector: ^1.0.3
  share_plus: ^11.0.0
  #path_provider: ^2.0.0
  flutter_file_dialog: ^3.0.2
  sensors_plus: ^4.0.0
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.1.0
  bloc: ^8.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dartx: ^1.1.0
  debug_overlay: ^1.0.0
  dropdown_button2: ^2.3.9
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.20.3
  flutter_list_view: ^1.1.22
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  flutter_secure_storage: ^9.0.0
  #flutter_share: ^2.0.0
  #share_plus: ^7.2.1 
  flutter_sliding_up_panel: ^2.0.1
  flutter_svg: ^2.0.9
  #flutter_web_auth_2: ^2.1.3
  flutter_appauth: ^8.0.2
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.0.3
  google_fonts: ^6.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.6.0
  overlay_dialog: ^0.2.2
  path_provider: ^2.0.11
  pdf: ^3.8.1
  popover: ^0.3.0+1
  printing: ^5.9.3
  provider: ^6.1.1
  shared_preferences: ^2.0.15
  trotter: ^2.2.0
  url_launcher: ^6.1.4
  
  pharmcat_dart_plugin:
    git:
      url: git@github.com:felix1717-r/pharmcat_dart_plugin.git
      ref: main 
 

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.0.3
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^1.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/tutorial/
    - assets/phenotype.json
    - assets/alleles/ABCG2_translation.json
    - assets/alleles/CACNA1S_translation.json
    - assets/alleles/CFTR_translation.json
    - assets/alleles/CYP2B6_translation.json
    - assets/alleles/CYP2C9_translation.json
    - assets/alleles/CYP2C19_translation.json
    - assets/alleles/CYP2D6_translation.json
    - assets/alleles/CYP3A4_translation.json
    - assets/alleles/CYP3A5_translation.json
    - assets/alleles/CYP4F2_translation.json
    - assets/alleles/DPYD_translation.json
    - assets/alleles/exemptions.json
    - assets/alleles/G6PD_translation.json
    - assets/alleles/IFNL3_translation.json
    - assets/alleles/location.json
    - assets/alleles/NAT2_translation.json
    - assets/alleles/NUDT15_translation.json
    - assets/alleles/RYR1_translation.json
    - assets/alleles/SLCO1B1_translation.json
    - assets/alleles/TPMT_translation.json
    - assets/alleles/UGT1A1_translation.json
    - assets/alleles/VKORC1_translation.json

    # phenotype → DPWG
    - assets/phenotype/dpwg/ABCG2.json
    - assets/phenotype/dpwg/CYP2B6.json
    - assets/phenotype/dpwg/CYP2C9.json
    - assets/phenotype/dpwg/CYP2C19.json
    - assets/phenotype/dpwg/CYP2D6.json
    - assets/phenotype/dpwg/CYP3A4.json
    - assets/phenotype/dpwg/CYP3A5.json
    - assets/phenotype/dpwg/DPYD.json
    - assets/phenotype/dpwg/NUDT15.json
    - assets/phenotype/dpwg/SLCO1B1.json
    - assets/phenotype/dpwg/TPMT.json
    - assets/phenotype/dpwg/UGT1A1.json
    - assets/phenotype/dpwg/VKORC1.json

    # phenotype → CPIC
    - assets/phenotype/cpic/ABCG2.json
    - assets/phenotype/cpic/CACNA1S.json
    - assets/phenotype/cpic/CFTR.json
    - assets/phenotype/cpic/CYP2B6.json
    - assets/phenotype/cpic/CYP2C9.json
    - assets/phenotype/cpic/CYP2C19.json
    - assets/phenotype/cpic/CYP2D6.json
    - assets/phenotype/cpic/CYP3A5.json
    - assets/phenotype/cpic/DPYD.json
    - assets/phenotype/cpic/G6PD.json
    - assets/phenotype/cpic/IFNL3.json
    - assets/phenotype/cpic/MT_RNR1.json
    - assets/phenotype/cpic/NUDT15.json
    - assets/phenotype/cpic/RYR1.json
    - assets/phenotype/cpic/SLCO1B1.json
    - assets/phenotype/cpic/TPMT.json
    - assets/phenotype/cpic/UGT1A1.json

    # guidence
    - assets/prescribing_guidance.json

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
