services:
  api:
    build:
      dockerfile: ./annotation-server/Dockerfile
      context: ../
    env_file: .env
    volumes:
      # mapped folder in the container needs to match the working dir found in the Dockerfile
      - ./data:/app/data:ro
    ports:
      - 8080:3000
    depends_on:
      - annotation-server-db
    profiles:
      - production

  annotation-server-db:
    image: postgres:13
    volumes:
      - annotation_server_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=annotation_db

volumes:
  annotation_server_db:
