name: Annotation Interface

on:
  push:
    paths:
      - '.github/workflows/annotation-interface.yml'
      - 'annotation-interface/**'

defaults:
  run:
    working-directory: ./annotation-interface

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
